### ISSUE TITLE
MachineLearning_Toolkit: Previous script not working after installer installation

### ISSUE THREAD

**Issue by BingWangUS** [BHoM/MachineLearning_Toolkit#42] opened 2020-07-31 13:57 UTC
#### Description:

Having this issue after a clean install from installer. 
1. Using Alphainstaller
2. Compile Python toolkit
3. Install Python toolkit
4. Compile ML toolkit
5. Install ML toolkit
6. Open the test script here
[MachineLearning#15-ScoreMethod_Testing.zip](https://github.com/BHoM/MachineLearning_Toolkit/files/5007365/MachineLearning.15-ScoreMethod_Testing.zip)

![image](https://user-images.githubusercontent.com/10835375/89041813-fd8df600-d313-11ea-92a0-eb6ad9ca0950.png)

**Comment by epignatelli** [comment] 2020-07-31 18:58
Currently, python files are not copied correctly to the BHoM folder.

We have an open pr that solves that - https://github.com/BHoM/BHoM_Installer/pull/82 - keep an eye for that to be merged!

**Comment by BingWangUS** [comment] 2020-07-31 20:22
> Currently, python files are not copied correctly to the BHoM folder.
> 
> We have an open pr that solves that - [BHoM/BHoM_Installer#82](https://github.com/BHoM/BHoM_Installer/pull/82) - keep an eye for that to be merged!

Hi Eduardo, after installer I also compile so those files are there. I guess this is not the cause but will keep an eye on the installer and test and report back.

**Comment by epignatelli** [comment] 2020-08-05 10:11
I followed your procedure and added a restart of Rhinoceros as a point 5b.
All working ok:

![image](https://user-images.githubusercontent.com/26899347/89400913-6efee780-d70c-11ea-98f6-fae693a4a8ce.png)


Di you restart the UI after installing the ML Toolkit?

**Comment by BingWangUS** [comment] 2020-08-06 22:38
Retesting this, confirm the script can work in Rhino 5 but not Rhino 6.

**Comment by epignatelli** [comment] 2020-08-07 08:03
Ok, thanks Bing - so I'll close this as duplicate of #31

**Closed as completed by epignatelli** 2020-08-07 08:03 UTC
Labels: type:bug

**Comment by BingWangUS** [comment] 2020-08-07 14:51
I can confirm the issue is caused by pandas - even though the previous scripts is not using pandas, it is importing all python files when initialising python, which will import pandas and then cause issue in Rhino 6.

Removing the following lines in Compute\__init__.py will make the previous script back to work, but of course, will cause trouble to python charts functionality.
 from .ClimateCharts import Diurnal
 from .ClimateCharts import UTCI
 from .ClimateCharts import Frequency
 from .ClimateCharts import Heatmap

So maybe only import the py scripts when needed could be a solution?
