### ISSUE TITLE
MachineLearning_Toolkit: Some components failed to work after the most recent installation

### ISSUE THREAD

**Issue by BingWangUS** [BHoM/MachineLearning_Toolkit#20] opened 2020-07-15 14:29 UTC
#### Description:

I did a installation with the following steps:
 1. Install daily alpha
 2. Compile Python_toolkit from master
 3. Compile MachineLearning_toolkit from master
 4. Use InstallPythonToolkit component
 5. Use InstallMachineLearningToolkit component

All the steps above worked well without issue, but then having some issue when opening a previous scripts.
![image](https://user-images.githubusercontent.com/10835375/87556054-37100180-c684-11ea-8ce6-d1a4da286f22.png)

As the tensor creation does not have a issue, I think the machine learning toolkit is installed correctly. However, the MinMaxScaler component ran into issue with invoke as below, my guess is that it may be some location issue that it cannot find the MinMaxScaler.py file, which is currently under C:\ProgramData\BHoM\python-3.7.3-embed-amd64\src\MachineLearning_Toolkit\MachineLearning_Engine\Compute folder.

- Error: Object reference not set to an instance of an object.
- Occured in  BH.Engine.Python.Compute.Invoke(PyObject module, String method, IEnumerable`1 args, Dictionary`2 kwargs)
     called from BH.Engine.MachineLearning.Compute.Invoke(String method, Object[] args)

#### Test file(s):

[MachineLearning#15-ScoreMethod.zip](https://github.com/BHoM/MachineLearning_Toolkit/files/4925785/MachineLearning.15-ScoreMethod.zip)

**Comment by epignatelli** [comment] 2020-07-15 15:16
Thanks @BingWangUS, would it be ok if we pick this up in the Friday call?

**Comment by BingWangUS** [comment] 2020-07-15 15:20
> Thanks @BingWangUS, would it be ok if we pick this up in the Friday call?

Of course. I agree it will be better to have a workshop\call on this for testing and debugging.

**Comment by BingWangUS** [comment] 2020-07-17 14:57
After the workshop, found the solution:
After running the installPython and installMachineLearning, close and reopen Rhino and Grasshopper will solve the problem. 

So the issue is Rhino\Grasshopper is only importing module when opening it for the first time. It will be great if we can streamline this process. Issue created #24

**Comment by epignatelli** [comment] 2020-07-30 12:14
Closing this as the issue is documented at: https://github.com/BHoM/MachineLearning_Toolkit/issues/24

**Closed as completed by epignatelli** 2020-07-30 12:14 UTC
Labels: type:bug
