### ISSUE TITLE
MachineLearning fails to load Python modules in Rhinoceros 6

### ISSUE THREAD

**Issue by epignatelli** [BHoM/MachineLearning_Toolkit#31] opened 2020-07-29 08:48 UTC
#### Description:

When loading the MachineLearning_Engine module, `pandas` gets loaded and for some weird reason it throws this error:
`AttributeError : type object 'pandas._libs.tslibs.conversion._TSObject' has no attribute 'reduce_cython`
This happens only whilst using Rhinoceros 6.
#### Steps to reproduce:

- Open Rhinoceros 6
- Install the toolkit   
- `Import` component with `pandas` argument

#### Expected behaviour:

It should not fail

#### Workarounds(s):

We currently have a workaround, which is to just use rhinoceros 5.

**Comment by epignatelli** [comment] 2020-08-21 14:24
From the Machine Learning call of 21/08/2020:

Possible workarouds:
- Lazily import modules
- Find a version of pandas that does not break

**Comment by BingWangUS** [comment] 2020-08-25 12:40
@epignatelli I did some testing. Installed several version of pandas but all seems having the same problem. (1.1.0, 1.0.0, 0.24.0 are failing with the same error, 0.23.0 failed to install).

Something interesting is that I found if we install cython and import cython before pandas, this can resolve the issue of some components in Rhino 6, for example, creating tensor will work. However, it is still failing on main functionality components such as Linear Regression. Does this give you some clue?

I uploaded a new branch (https://github.com/BHoM/MachineLearning_Toolkit/tree/MachineLearning_Toolkit-%2331-TryToFixPandas) for the testing.

**Comment by epignatelli** [comment] 2020-08-27 08:19
Thanks very much @BingWangUS that's extremely helpful.

Digging a bit further, I think it would be best to track this https://github.com/cython/cython/issues/1953 - which is the underlying problem.

I have done some other tests:
- Inflated the `Python37.zip` into the `Lib` folder
- Used cython 0.29

But none of them made a difference.

**Comment by epignatelli** [comment] 2020-08-27 08:20
Let's keep the branch open for future tests and for clarity.

**Comment by jamesramsden-bh** [comment] 2023-01-05 11:34
Closed as installation has changed since issue was last commented on, and now appears to install correctly on my machine.

**Closed as not planned by jamesramsden-bh** 2023-01-05 11:34 UTC
Labels: type:bug
